# Copyright (c) 1998 Lawrence Livermore National Security, LLC and other
# HYPRE Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

###############################################################################
##  All configurable variables are defined in the file named Makefile.config.in
##  When Autoconf is run, it will create a file named Makefile.config which
##  will have all of the configurable variables replaced with their values.
###############################################################################



srcdir = .
top_srcdir = ..
prefix = /home/jiping/FENGSim/toolkit/NLA/hypre/src/../../install/hypre
exec_prefix = ${prefix}



HYPRE_RELEASE_NAME    = hypre
HYPRE_RELEASE_VERSION = 2.31.0
HYPRE_RELEASE_DATE    = 2024/02/14
HYPRE_RELEASE_TIME    = 00:00:00
HYPRE_RELEASE_BUGS    = https://github.com/hypre-space/hypre/issues

HYPRE_SRC_TOP_DIR = /home/jiping/FENGSim/toolkit/NLA/hypre/src
HYPRE_BUILD_DIR   = /home/jiping/FENGSim/toolkit/NLA/hypre/src/hypre

HYPRE_INSTALL_DIR = /home/jiping/FENGSim/toolkit/NLA/hypre/src/../../install/hypre
HYPRE_LIB_INSTALL = ${exec_prefix}/lib
HYPRE_INC_INSTALL = ${prefix}/include

HYPRE_LIB_SUFFIX = .a

.SUFFIXES:
.SUFFIXES: .o .obj .f .c .C .cxx .cc

FC        = mpif77
FFLAGS    = -O2 -g -O2 $(FC_COMPILE_FLAGS)

CC        = mpicc
CFLAGS    = -O2  -DHAVE_CONFIG_H $(C_COMPILE_FLAGS)

CXX       = mpic++
CXXFLAGS  = -O2  -DHAVE_CONFIG_H $(CXX_COMPILE_FLAGS)

CUCC      =  ${CUDA_ARCH}
CUFLAGS   =   -DHAVE_CONFIG_H ${C_COMPILE_FLAGS}

.f.o:
	$(FC) $(FFLAGS) -c $<
.c.o:
	$(CC) $(CFLAGS) -c $<
.C.o:
	$(CXX) $(CXXFLAGS) -c $<
.cxx.o:
	$(CXX) $(CXXFLAGS) -c $<
.cc.o:
	$(CXX) $(CXXFLAGS) -c $<
ifeq ($(CUCC), )
.c.obj:
	$(CC) $(CFLAGS) -c $< -o $@
else
.c.obj:
	$(CUCC) $(CUFLAGS) -c $< -o $@
endif

LINK_FC  = ${FC}
LINK_CC  = ${CC}
LINK_CXX = ${CXX}

BUILD_FC_SHARED     = 
BUILD_CC_SHARED     = 
BUILD_CXX_SHARED    = 
SHARED_COMPILE_FLAG = 
SHARED_BUILD_FLAG   = 
SHARED_SET_SONAME   = 
SHARED_OPTIONS      = 

BUILD_PYTHON = 0
PYTHON       = 

BUILD_JAVA = 0

AR     = ar -rcu
RANLIB = ranlib

LDFLAGS = 
LIBS    =    -lm ${CALIPER_LIBS} ${HYPRE_CUDA_LIBS} ${HYPRE_HIP_LIBS} ${HYPRE_SYCL_LIBS} ${HYPRE_RAJA_LIB_DIR} ${HYPRE_RAJA_LIB} ${HYPRE_KOKKOS_LIB_DIR} ${HYPRE_KOKKOS_LIB} ${HYPRE_UMPIRE_LIB_DIR} ${HYPRE_UMPIRE_LIB} ${HYPRE_MAGMA_LIB_DIR} ${HYPRE_MAGMA_LIB}
FLIBS   = 

INCLUDES = ${CALIPER_INCLUDE} ${HYPRE_CUDA_INCLUDE} ${HYPRE_HIP_INCLUDE} ${HYPRE_SYCL_INCLUDE} ${HYPRE_RAJA_INCLUDE} ${HYPRE_KOKKOS_INCLUDE} ${HYPRE_UMPIRE_INCLUDE} ${HYPRE_MAGMA_INCLUDE} ${HYPRE_NAP_INCLUDE}

##################################################################
##  LAPACK Library Flags
##################################################################
LAPACKLIBS      = 
LAPACKLIBDIRS   = 

##################################################################
##  BLAS Library Flags
##################################################################
BLASLIBS        = 
BLASLIBDIRS     = 

##################################################################
##  MPI options
##################################################################
MPIINCLUDE = 
MPILIBDIRS = 
MPILIBS    =  
MPIFLAGS   = 

##################################################################
##  Node Aware MPI options
##################################################################
HYPRE_NAP_INCLUDE = 

##################################################################
##  CUDA options
##################################################################
HYPRE_CUDA_PATH    = 
HYPRE_CUDA_INCLUDE = 
HYPRE_CUDA_LIBS    = 
CUDA_ARCH          = 

##################################################################
##  HIP options
##################################################################
HYPRE_HIP_INCLUDE = 
HYPRE_HIP_LIBS    = 

##################################################################
##  SYCL options
##################################################################
HYPRE_SYCL_INCLUDE=
HYPRE_SYCL_LIBS=

##################################################################
##  Caliper options
##################################################################
CALIPER_INCLUDE = 
CALIPER_LIBS    = 

##################################################################
##  Euclid, ParaSails, pilut options
##################################################################
HYPRE_DISTRIBUTED_LS_DIR = /home/jiping/FENGSim/toolkit/NLA/hypre/src/distributed_ls
HYPRE_EUCLID_FILES       = /home/jiping/FENGSim/toolkit/NLA/hypre/src/distributed_ls/Euclid/*.o
HYPRE_PARASAILS_FILES    = /home/jiping/FENGSim/toolkit/NLA/hypre/src/distributed_ls/ParaSails/*.o
HYPRE_PILUT_FILES        = /home/jiping/FENGSim/toolkit/NLA/hypre/src/distributed_ls/pilut/*.o

##################################################################
##  MAGMA options
##################################################################
HYPRE_MAGMA_LIB_DIR      = 
HYPRE_MAGMA_INCLUDE      = 
HYPRE_MAGMA_LIB          = 

##################################################################
##  SuperLU options
##################################################################
SUPERLU_INCLUDE = 
SUPERLU_LIBS    = 

##################################################################
##  DsuperLU options
##################################################################
DSUPERLU_INCLUDE = 
DSUPERLU_LIBS    = 

##################################################################
##  FEI options
##################################################################
HYPRE_FEI_SRC_DIR       = 
HYPRE_FEI_BASE_DIR      = 
HYPRE_FEI_SUBDIRS       = 
HYPRE_FEI_HYPRE_FILES   = 
HYPRE_FEI_FEMLI_FILES   = 

##################################################################
##  RAJA options
##################################################################
HYPRE_RAJA_LIB_DIR      = 
HYPRE_RAJA_INCLUDE      = 
HYPRE_RAJA_LIB          = 

##################################################################
##  kokkos options
##################################################################
HYPRE_KOKKOS_SRC_DIR    = 
HYPRE_KOKKOS_LIB_DIR    = 
HYPRE_KOKKOS_INCLUDE    = 
HYPRE_KOKKOS_LIB        = 

##################################################################
##  UMPIRE options
##################################################################
HYPRE_UMPIRE_LIB_DIR      = 
HYPRE_UMPIRE_INCLUDE      = 
HYPRE_UMPIRE_LIB          = 
